C          CPARAM.        PARAMETER STATEMENTS FOR RTTOV SUITE.
C                         VERSION 2.
C          J.R.EYRE       *ECMWF*        27/01/94.
C          R.W. SAUNDERS MODIFIED TO ALLOW MORE THAN 2 SATS
C
      INTEGER   JPTOVS,JPDMSP,JPMET,JPGOES,JPGMS,JPNSAT,JPLEV,
     &     JPNAV,JPNSAV,JPNSSV,JPNCV,JPPF,
     &     JPCH,JPHIR,JPMSU,JPAMSU,JPSSU,JPCHUS,JPCHPF,
     &     JPCOFM,JPCOFW,JPCOFO,JPST,IU1
      REAL PI,DEG2RAD,RCNV
C
      PARAMETER (JPTOVS=12)         ! MAX NO. OF SATS IN COEF FILE
      PARAMETER (JPDMSP= 5)         ! MAX NO. OF SATS IN COEF FILE
      PARAMETER (JPMET = 3)         ! MAX NO. OF SATS IN COEF FILE
      PARAMETER (JPGOES= 2)         ! MAX NO. OF SATS IN COEF FILE
      PARAMETER (JPGMS = 5)         ! MAX NO. OF SATS IN COEF FILE
      PARAMETER (JPNSAT=12)         ! TOTAL MAX TO BE USED
      PARAMETER (JPLEV=43)          ! NO. OF PRESSURE LEVELS
      PARAMETER (JPNAV=4)           ! NO. OF PROFILE VARIABLES
      PARAMETER (JPNSAV=5)          ! NO. OF SURFACE AIR VARIABLES
      PARAMETER (JPNSSV=1)          ! NO. OF SKIN VARIABLES
      PARAMETER (JPNCV=2)           ! NO. OF CLOUD VARIABLES
      PARAMETER (JPPF=1)           ! MAX NO. PROFILES 
C      PARAMETER (JPPF=2)            ! MAX NO. PROFILES (normally set to
C                                   ! 1 except for vector machines)
      PARAMETER (JPCH=47)           ! MAX. NO. OF TOVS CHANNELS
C      PARAMETER (JPCH=27)           ! MAX. NO. OF TOVS CHANNELS
      PARAMETER (JPHIR=20)          ! MAX. NO. OF HIRS CHANNELS
      PARAMETER (JPMSU=4)           ! MAX. NO. OF MSU CHANNELS
      PARAMETER (JPAMSU=20)         ! MAX. NO. OF AMSU CHANNELS
      PARAMETER (JPSSU=3)           ! MAX. NO. OF SSU CHANNELS
C      PARAMETER (JPCHUS=25)         ! MAX. NO. OF CHANNELS USED TOVS
      PARAMETER (JPCHUS=39)         ! MAX. NO. OF CHANNELS USED ATOVS
      PARAMETER (JPCHPF=JPPF*JPCHUS)  ! MAX NO. OF PROFS * CHANS USED
      PARAMETER (JPCOFM=10)         ! MIXED GAS COEFFS (MAX)
      PARAMETER (JPCOFW=10)         ! WATER VAPOUR COEFFS (MAX)
      PARAMETER (JPCOFO=10)         ! OZONE COEFFS
      PARAMETER (JPST=10)           ! MAX NO. OF SURFACE TYPES
C     PARAMETER (IU1=10)
C      
      PARAMETER(PI=3.1415926535,DEG2RAD=PI/180.)
      PARAMETER(RCNV=6.03504E5)     ! kg/kg--> ppmv
