C          /GEOCON/  SATELLITE GEOMETRY CONSTANTS
C               VERSION 2 CHANGE: * ALL SATS
C          12/8/92.
      COMMON/GEOCON/HTSAT,RATOE
      REAL HTSAT(JPNSAT),RATOE(JPNSAT)
C          HTSAT: SATELLITE ALTITUDE IN KM
C          RATOE: RATIO SATELLITE-ORBIT:EARTH RADII
C
C
C
C
