C          /PRFCON/  ATMOSPHERIC PROFILE CONSTANTS
C          4/12/90.
C     
      COMMON/PRFCON/XPRES,XPRES2,DPRES,WPRES3,WMIN,NLEVW1,
     &     NLEVW2,NLEVW,NRTTOV,OZMIN1
C
      REAL XPRES(JPLEV),XPRES2(JPLEV),DPRES(JPLEV),WPRES3(JPLEV),
     &     WMIN,OZMIN1
      INTEGER   NLEVW1,NLEVW2,NLEVW,NRTTOV
C
C          XPRES: STD PRESS LEVELS FOR TRANSMITTANCE (AND, CURRENTLY,
C                 RT) CALCULATION; FROM TOP DOWN; IN MB=HPA
C          XPRES2: XPRES**2; IN MB**2
C          DPRES: INTERVALS BETWEEN STD PRESS LEVELS; IN MB
C          WPRES3: (XPRES/REF.PRESS)**3,
C                  WHERE REF.PRESS=XPRES(NLEVW2+1)
C          WMIN: MIN WATER VAPOUR SPECIFIC HUMIDITY; IN G/KG
C          NLEVW1: UPPER LEVEL FOR WATER VAPOUR EXTRAPOLATION
C          NLEVW2: LOWER LEVEL FOR WATER VAPOUR EXTRAPOLATION
C          NLEVW: UPPER LEVEL FOR WATER VAPOUR TRANSMITTANCE CALC
C                 (ASSUMED TRANSMITTANCE=0. ABOVE THIS)
C          NRTTOV: RTTOV VERSION NUMBER
C          OZMIN1: MINIMUM OZONE VALUE IN PPMV SET IN RTTVI
C
C
C
