C          /PRFLIM/  ATMOSPHERIC PROFILE LIMITS
C          21/4/98.
      COMMON/PRFLIM/TMAX,TMIN,QMAX,QMIN,OZMAX,OZMIN
      REAL TMAX(JPLEV,JPNSAT),TMIN(JPLEV,JPNSAT),QMAX(JPLEV,JPNSAT)
      REAL QMIN(JPLEV,JPNSAT),OZMAX(JPLEV,JPNSAT),OZMIN(JPLEV,JPNSAT)
C      
