C          /PRFREF/  REFERENCE PROFILE IN TRANSMITTANCE CALC
C          4/12/90.
      COMMON/PRFREF/PREF,TREF,WREF,TOZREF,OZREF
      REAL PREF(JPLEV,JPNSAT)
      REAL TREF(JPLEV,JPNSAT),WREF(JPLEV,JPNSAT),TOZREF(JPLEV,JPNSAT)
      REAL OZREF(JPLEV,JPNSAT)
C          PREF: REFERENCE PRESSURE PROFILE IN HPA
C          TREF: REFERENCE TEMPERATURE PROFILE FOR HUMIDITY IN K
C          WREF: REFERENCE SPECIFIC HUMIDITY PROFILE IN KG/KG
C          TOZREF: REFERENCE TEMPERATURE PROFILE FOR OZONE IN K
C          OZREF: REFERENCE OZONE PROFILE IN PPMV
C
C
C
C
