SUBROUTINE OBJFN( MODE,N,X,OBJF,OBJGRD,NSTATE )
  !***************************************************************
  !***************************************************************
  !**   This routine was generated by the                         **
  !**   Tangent linear and Adjoint Model Compiler,  TAMC 5.3.0    **
  !***************************************************************
  !***************************************************************
  !==============================================
  !     all entries are defined explicitly
  !==============================================
  implicit none
  save
  !
  integer mode
  integer n
  double precision x(n)
  double precision objf
  double precision objgrd(n)
  integer nstate
  integer irc
  character*16 myname
  data myname /'OBJFN'/
  !
  integer, parameter :: ne=6
  real :: ie(ne)
  real :: e(ne)
  common /cncprob/ e
  integer :: ii
  real a,a2,a3,a4
  real b,b2,b3,b4
  real c,c2,c3,c4
  real d,d2,d3,d4
  real s1,s1da,s1db,s1dc,s1dd
  real s2,s2da,s2db,s2dc,s2dd
  real s3,s3da,s3db,s3dc,s3dd
  real s4,s4da,s4db,s4dc,s4dd
  real, parameter :: j = 0.75D0
  !     
  !write(*,*) 'OBJFN: Entering.',x
  objf = 0.0
  objgrd(:) = 0.0
  !
  a=x(1)
  a2 = a**2
  a3 = a**3
  a4 = a**4
  !
  b=x(2)
  b2 = b**2
  b3 = b**3
  b4 = b**4
  !
  c=x(3)
  c2 = c**2
  c3 = c**3
  c4 = c**4
  !
  d=x(4)
  d2 = d**2
  d3 = d**3
  d4 = d**4
  !
  s1 = a &
       & +c &
       & -E(1)
  s2 = a2 &
       & +2.0D0*a*c &
       & +b2 &
       & +6.0D0*b*d*j &
       & +3.0D0*c2*j &
       & +15.0D0*d2 &
       & -E(2)
  s3 = a3 &
       & +3.0D0*a2*c &
       & +3.0D0*a*b2 &
       & +18.0D0*a*b*d*j &
       & +9.0D0*a*c2*j &
       & +45.0D0*a*d2 &
       & +9.0D0*b2*c*j &
       & +90.0D0*b*c*d &
       & +15.0D0*c3 &
       & +315.0D0*c*d2 &
       & -E(3)
  s4 = a4 &
       & +4.0D0*a3*c &
       & +6.0D0*a2*b2 &
       & +36.0D0*a2*b*d*j &
       & +18.0D0*a2*c2*j &
       & +90.0D0*a2*d2 &
       & +36.0D0*a*b2*c*j &
       & +360.0D0*a*b*c*d &
       & +60.0D0*a*c3 &
       & +1260.0D0*a*c*d2 &
       & +3.0D0*b4*j &
       & +60.0D0*b3*d &
       & +90.0D0*b2*c2 &
       & +630.0D0*b2*d2 &
       & +1260.0D0*b*c2*d &
       & +3780.0D0*b*d3 &
       & +105.0D0*c4 &
       & +5670.0D0*c2*d2 &
       & +10395.0D0*d4 &
       & -E(4)
  !
  s1da = 1.0D0
  s1db = 0.0D0
  s1dc = 1.0D0
  s1dd = 0.0D0
  !
  s2da = 2.0D0*a &
       & +2.0D0*c
  s2db = 2.0D0*b &
       & +6.0D0*d*j
  s2dc = 2.0D0*a &
       & +6.0D0*c*j
  s2dd = 6.0D0*b*j &
       & +30.0D0*d

  s3da = 3.0D0*a2 &
       & +6.0D0*a*c &
       & +3.0D0*b2 &
       & +18.0D0*b*d*j &
       & +9.0D0*c2*j &
       & +45.0D0*d2
  s3db = 6.0D0*a*b &
       & +18.0D0*a*d*j &
       & +18.0D0*b*c*j &
       & +90.0D0*c*d
  s3dc = 3.0D0*a2 &
       & +18.0D0*a*c*j &
       & +9.0D0*b2*j &
       & +90.0D0*b*d &
       & +45.0D0*c2 &
       & +315.0D0*d2
  s3dd = 18.0D0*a*b*j &
       & +90.0D0*a*d &
       & +90.0D0*b*c &
       & +630.0D0*c*d

  s4da = 4.0D0*a3 &
       & +12.0D0*a2*c &
       & +12.0D0*a*b2 &
       & +72.0D0*a*b*d*j &
       & +36.0D0*a*c2*j &
       & +180.0D0*a*d2 &
       & +36.0D0*b2*c*j &
       & +360.0D0*b*c*d &
       & +60.0D0*c3 &
       & +1260.0D0*c*d2
  s4db = 12.0D0*a2*b &
       & +36.0D0*a2*d*j &
       & +72.0D0*a*b*c*j &
       & +360.0D0*a*c*d &
       & +12.0D0*b3*j &
       & +180.0D0*b2*d &
       & +180.0D0*b*c2 &
       & +1260.0D0*b*d2 &
       & +1260.0D0*c2*d &
       & +3780.0D0*d3
  s4dc = 4.0D0*a3 &
       & +36.0D0*a2*c*j &
       & +36.0D0*a*b2*j &
       & +360.0D0*a*b*d &
       & +180.0D0*a*c2 &
       & +1260.0D0*a*d2 &
       & +180.0D0*b2*c &
       & +2520.0D0*b*c*d &
       & +420.0D0*c3 &
       & +11340.0D0*c*d2
  s4dd = 36.0D0*a2*b*j &
       & +180.0D0*a2*d &
       & +360.0D0*a*b*c &
       & +2520.0D0*a*c*d &
       & +60.0D0*b3 &
       & +1260.0D0*b2*d &
       & +1260.0D0*b*c2 &
       & +11340.0D0*b*d2 &
       & +11340.0D0*c2*d &
       & +41580.0D0*d3

  objf= s1*s1 + s2*s2 + s3*s3 + s4*s4

  objgrd(1)=2.0D0*(s1*s1da + s2*s2da + s3*s3da + s4*s4da)
  objgrd(2)=2.0D0*(s1*s1db + s2*s2db + s3*s3db + s4*s4db)
  objgrd(3)=2.0D0*(s1*s1dc + s2*s2dc + s3*s3dc + s4*s4dc)
  objgrd(4)=2.0D0*(s1*s1dd + s2*s2dd + s3*s3dd + s4*s4dd)
  !
  !write(*,'(A,10(X,F20.7))') 'Objfn:',objf,objgrd,x
  !     
  RETURN
  !     
  ENTRY IOBJFN (ie,irc)
  !     store moments
  do ii = 1,ne
     e(ii) = ie(ii)
  end do
  !     
  RETURN
end SUBROUTINE OBJFN
